In [ ]:
# Normal Python array

arr = [1, 3 ,5]
multiplication = arr*3
print(multiplication)

[1, 3, 5, 1, 3, 5, 1, 3, 5]


In [3]:
# Numpy Array

import numpy as np
array1 = np.array([1,2,3,4,5])
array1 = array1*3
print(array1) 

[ 3  6  9 12 15]


In [16]:
#NdArray

arr1 = np.array([1,2,3])
print("1D Array",arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array", arr2)

arr3 = np.array([
    [
        [1,2,3],
        [3,5,6]
    ],
    [
        [3,4,6],
        [7,8,2]
    ],
])
print("3D array", arr3)
print(arr3.shape)


1D Array [1 2 3]
2D array [[1 2 3]
 [4 5 6]]
3D array [[[1 2 3]
  [3 5 6]]

 [[3 4 6]
  [7 8 2]]]
(2, 2, 3)


In [19]:
# Dimension, Size, Data type, Shape

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr1.dtype)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

1
2
3
3
6
12
int64
(3,)
(2, 3)
(2, 2, 3)


In [ ]:
#Type Upcast --> bool → int → float → string

arr = np.array([1,2,3.1])
print(arr.dtype)

arr1 = np.array([1,2.3,"Hello"])
print(arr1.dtype)

arr3 = np.array([True, 1.3,4])
print(arr3.dtype)


float64
<U32
float64


In [26]:
# Set Data type, Change data type

arr = np.array([1,2,3], dtype= np.int16)
print(arr.dtype)
print(arr)

arr1 = arr.astype(np.int32)
print(arr1.dtype)

int16
[1 2 3]
int32


In [ ]:
arr = [1,2,3.5]
arr = np.array(arr, dtype=np.int32)
print(arr)

arr_mixed = [1,3,"Hi",True]
arr_Mixed1= np.array(arr_mixed)
print(arr_Mixed1)
print(arr_Mixed1.shape)





[1 2 3]
['1' '3' 'Hi' 'True']
(4,)


In [ ]:
# Tuple
tuple = (1, 4, 5)
arr = np.array(tuple,dtype = np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

# Set
set = {1,2,3,4,4,5}
print(set)
arr = np.array(list(set))
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.ndim)

#Dictionary
dictionary = {'a': 12, 'b': 10, 'c': 15, }
print(dictionary.keys())
print(dictionary.values())
print(dictionary.items())

arr = np.array(list(dictionary.keys()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.array (list(dictionary.values()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.array (list(dictionary.items()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

int32
[1 4 5]
<class 'numpy.ndarray'>
int16
1


In [10]:
dictionary = {'a': 12, 'b': 10, 'c': 15, }
print(dictionary.keys())
print(dictionary.values())
print(dictionary.items())

arr = np.array(list(dictionary.keys()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.array (list(dictionary.values()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.array (list(dictionary.items()))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

dict_keys(['a', 'b', 'c'])
dict_values([12, 10, 15])
dict_items([('a', 12), ('b', 10), ('c', 15)])
['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[12 10 15]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[['a' '12']
 ['b' '10']
 ['c' '15']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [22]:
#ndarray Creating from scratch

arr = np.zeros((2,3), dtype=np.int8)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.zeros_like(arr)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones((2,3), dtype= np.int8)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.ones_like(arr)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty ((4,3), dtype=np.int16)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.empty_like (arr)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full ((4,3),np.inf)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full_like(arr,np.inf, dtype=np.float64)
print (arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
(2, 3)
2
6
[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
(2, 3)
2
6
[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
(2, 3)
2
6
[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
(2, 3)
2
6
[[12  0  0]
 [ 0 10  0]
 [ 0  0 15]
 [ 0  0  0]]
<class 'numpy.ndarray'>
(4, 3)
2
12
[[  2536 -19555  32762]
 [     0 -32000  -5874]
 [   619      0      2]
 [     0      3      0]]
<class 'numpy.ndarray'>
(4, 3)
2
12
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
(4, 3)
2
12
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
(4, 3)
2
12


In [27]:
# Array creation with random values

arr = np.random.rand(2,3) #np.random.rand(shape)
print(arr)
print(arr.shape)
print(type(arr))
print(arr.ndim)
print(arr.size)

# np.random.rand(start, end, (shape))
arr = np.random.randint(1,10, (2,3))
print(arr)
print(arr.shape)
print(type(arr))
print(arr.ndim)
print(arr.size)



[[0.80603232 0.72974015 0.11582317]
 [0.34733564 0.11617039 0.83779644]]
(2, 3)
<class 'numpy.ndarray'>
2
6
[[8 1 5]
 [1 6 7]]
(2, 3)
<class 'numpy.ndarray'>
2
6


In [31]:
# Array creation with range function

array = np.arange(1,10,1)
matrix = array.reshape(3,3)

print(array)
print(matrix)
print(array.shape)
print(array.dtype)
print(type(array))
print(array.size)

array = np.linspace( 0 ,4,5)
print(array)
print(matrix)
print(array.shape)
print(array.dtype)
print(type(array))
print(array.size)

array = np.logspace(0,4,6, base=3)
print(array)
print(matrix)
print(array.shape)
print(array.dtype)
print(type(array))
print(array.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(9,)
int64
<class 'numpy.ndarray'>
9
[0. 1. 2. 3. 4.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(5,)
float64
<class 'numpy.ndarray'>
5
[ 1.          2.40822469  5.79954613 13.96661017 33.63473537 81.        ]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(6,)
float64
<class 'numpy.ndarray'>
6


In [38]:
diagonal_matrix = np.diag([1,2,3,4,])
print(diagonal_matrix)
print(diagonal_matrix.shape)

identity_matrix = np.eye(4)
print(identity_matrix)
print(identity_matrix.shape)

matrix = np.eye(3,4,1)
print(matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [42]:

# Indexing and Slicing
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])

print(arr1)
print(arr2)

arr1[1]= 200
print(arr1)

arr2[1][2]= 50
print(arr2)

# 1D array Slicing : 1d = arr[start:end:step]
arr1_mod = arr1[1:4]. copy()
arr1[2]=4

arr1_mod[2]=30
print(arr1_mod)



[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
[ 10 200  30  40  50]
[[ 1  2  3]
 [ 4  5 50]]
[200  30  30]


In [43]:
list1 = np.array([10, 20, 50])
print(list1[[0,1,2]])

[10 20 50]


In [44]:
print(arr2)
print(arr2[0,1],[1,2])

print(arr2[arr>1])
arr2[arr2>2] = 0;
print(arr2)

[[ 1  2  3]
 [ 4  5 50]]
2 [1, 2]
[ 1  3  5 50]
[[1 2 0]
 [0 0 0]]
