In [ ]:
# Normal Python array

arr = [1, 3 ,5]
multiplication = arr*3
print(multiplication)

[1, 3, 5, 1, 3, 5, 1, 3, 5]


In [ ]:
# Numpy Array

import numpy as np
array1 = np.array([1,2,3,4,5])
array1 = array1*3
print(array1) 

[ 3  6  9 12 15]


In [16]:
#NdArray

arr1 = np.array([1,2,3])
print("1D Array",arr1)

arr2 = np.array([[1,2,3],[4,5,6]])
print("2D array", arr2)

arr3 = np.array([
    [
        [1,2,3],
        [3,5,6]
    ],
    [
        [3,4,6],
        [7,8,2]
    ],
])
print("3D array", arr3)
print(arr3.shape)


1D Array [1 2 3]
2D array [[1 2 3]
 [4 5 6]]
3D array [[[1 2 3]
  [3 5 6]]

 [[3 4 6]
  [7 8 2]]]
(2, 2, 3)


In [19]:
# Dimension, Size, Data type, Shape

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr1.dtype)

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

1
2
3
3
6
12
int64
(3,)
(2, 3)
(2, 2, 3)


In [ ]:
#Type Upcast --> bool → int → float → string

arr = np.array([1,2,3.1])
print(arr.dtype)

arr1 = np.array([1,2.3,"Hello"])
print(arr1.dtype)

arr3 = np.array([True, 1.3,4])
print(arr3.dtype)


float64
<U32
float64


In [26]:
# Set Data type, Change data type

arr = np.array([1,2,3], dtype= np.int16)
print(arr.dtype)
print(arr)

arr1 = arr.astype(np.int32)
print(arr1.dtype)

int16
[1 2 3]
int32


In [ ]:
arr = [1,2,3.5]
arr = np.array(arr, dtype=np.int32)
print(arr)

arr_mixed = [1,3,"Hi",True]
arr_Mixed1= np.array(arr_mixed)
print(arr_Mixed1)
print(arr_Mixed1.shape)





[1 2 3]
['1' '3' 'Hi' 'True']
(4,)
